course=input("Write  course name:")
Your_name=  input("Your name: ")
Your_last_name=input("Your last name: ")
nickname=input("nickname: ")
grade=input("grade: ")
pythonExpert=bool(input("pythonExpert:"))
print( "course: "+course)
print(f'student: {Your_name} {Your_last_name}')
print(f'nickname: {nickname}')
print(f'grade: {grade}')
print(f'PythonExpert: {pythonExpert}')